// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHf4KOmW4_QrTZHuJoDS06nVzoSMFsBYw',
    appId: '1:750597377279:web:23da5723951bebf03010ca',
    messagingSenderId: '750597377279',
    projectId: 'spydemedia',
    authDomain: 'spydemedia.firebaseapp.com',
    storageBucket: 'spydemedia.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADznGjwhOoQ0PQVjUa89dJIVV7CYMOoWo',
    appId: '1:750597377279:android:12702afd29f6a8b63010ca',
    messagingSenderId: '750597377279',
    projectId: 'spydemedia',
    storageBucket: 'spydemedia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5O5NbjHqrmRO3pYYjtBS5ZQK4nMdG-sk',
    appId: '1:750597377279:ios:3b6e8090f24aaa1b3010ca',
    messagingSenderId: '750597377279',
    projectId: 'spydemedia',
    storageBucket: 'spydemedia.appspot.com',
    iosClientId: '750597377279-rhmgujl3c3d30ps6bjulnknabe30gkbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mainapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5O5NbjHqrmRO3pYYjtBS5ZQK4nMdG-sk',
    appId: '1:750597377279:ios:68c06ebfc961a7713010ca',
    messagingSenderId: '750597377279',
    projectId: 'spydemedia',
    storageBucket: 'spydemedia.appspot.com',
    iosClientId: '750597377279-u1qgpoha1edvbf7pjg614rplhrb451c7.apps.googleusercontent.com',
    iosBundleId: 'com.example.mainapp.RunnerTests',
  );
}
